package PlantUML.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.base.BasePropertyConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SEnumerationLiteral;
import java.util.Map;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.runtime.PropertyConstraintsDescriptor;
import java.util.HashMap;
import org.jetbrains.mps.openapi.language.SInterfaceConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class NonAccessModifierEntityElement_Constraints extends BaseConstraintsDescriptor {
  public NonAccessModifierEntityElement_Constraints() {
    super(CONCEPTS.NonAccessModifierEntityElement$$n);
  }

  public static class NonAccessModifier_Property extends BasePropertyConstraintsDescriptor {
    public NonAccessModifier_Property(ConstraintsDescriptor container) {
      super(PROPS.nonAccessModifier$kcI7, container, false, true, false);
    }
    @Override
    public void setPropertyValue(SNode node, Object propertyValue) {
      staticSetPropertyValue(node, SPropertyOperations.castEnummember(propertyValue));
    }
    private static void staticSetPropertyValue(SNode node, SEnumerationLiteral propertyValue) {
      SPropertyOperations.set(node, PROPS.showNonAccessModifier$oF96, true);
      SPropertyOperations.setEnum(node, PROPS.nonAccessModifier$kcI7, propertyValue);
    }
  }
  @Override
  protected Map<SProperty, PropertyConstraintsDescriptor> getSpecifiedProperties() {
    Map<SProperty, PropertyConstraintsDescriptor> properties = new HashMap<SProperty, PropertyConstraintsDescriptor>();
    properties.put(PROPS.nonAccessModifier$kcI7, new NonAccessModifier_Property(this));
    return properties;
  }

  private static final class CONCEPTS {
    /*package*/ static final SInterfaceConcept NonAccessModifierEntityElement$$n = MetaAdapterFactory.getInterfaceConcept(0x2ff0a41f288043b3L, 0xa889f912d65b3892L, 0x1a5c6983052038d9L, "PlantUML.structure.NonAccessModifierEntityElement");
  }

  private static final class PROPS {
    /*package*/ static final SProperty nonAccessModifier$kcI7 = MetaAdapterFactory.getProperty(0x2ff0a41f288043b3L, 0xa889f912d65b3892L, 0x1a5c6983052038d9L, 0x1a5c6983052038dbL, "nonAccessModifier");
    /*package*/ static final SProperty showNonAccessModifier$oF96 = MetaAdapterFactory.getProperty(0x2ff0a41f288043b3L, 0xa889f912d65b3892L, 0x1a5c6983052038d9L, 0x1a5c69830521497dL, "showNonAccessModifier");
  }
}
