package PlantUML.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_NonAccessModifier extends EnumerationDescriptorBase {

  public EnumerationDescriptor_NonAccessModifier() {
    super(0x2ff0a41f288043b3L, 0xa889f912d65b3892L, 0x1a5c6983051cdee4L, "NonAccessModifier", "r:5ffd829d-cb20-4a43-9201-504c19294a4a(PlantUML.structure)/1899509154290917092");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_static_0 = new EnumerationDescriptor.MemberDescriptor("static", "{static}", 0x1a5c6983051cdee5L, "r:5ffd829d-cb20-4a43-9201-504c19294a4a(PlantUML.structure)/1899509154290917093");
  private final EnumerationDescriptor.MemberDescriptor myMember_abstract_0 = new EnumerationDescriptor.MemberDescriptor("abstract", "{abstract}", 0x1a5c6983051cdee6L, "r:5ffd829d-cb20-4a43-9201-504c19294a4a(PlantUML.structure)/1899509154290917094");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x2ff0a41f288043b3L, 0xa889f912d65b3892L, 0x1a5c6983051cdee4L, 0x1a5c6983051cdee5L, 0x1a5c6983051cdee6L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_static_0, myMember_abstract_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "static":
        return myMember_static_0;
      case "abstract":
        return myMember_abstract_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
